In [1]:
import numpy as np
import pandas as pd

#reading dataset
dataset = pd.read_csv("decision_Tree_dataset.csv")

#perform label encoding
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
dataset = dataset.apply(LabelEncoder().fit_transform)
print(dataset)

    AGE  INCOME  Gender  Maritial  Buys
0     1       0       1         1     0
1     1       0       1         0     0
2     0       0       1         1     1
3     2       2       1         1     1
4     2       1       0         1     1
5     2       1       0         0     0
6     0       1       0         0     1
7     1       2       1         1     0
8     1       1       0         0     1
9     2       2       0         1     1
10    1       2       0         0     1
11    0       2       1         0     1
12    0       0       0         1     1
13    2       2       1         0     0


In [2]:
x = dataset.iloc[ : ,  : -1]
y = dataset['Buys']

x = np.asarray(x)
print(x)
print(y)


[[1 0 1 1]
 [1 0 1 0]
 [0 0 1 1]
 [2 2 1 1]
 [2 1 0 1]
 [2 1 0 0]
 [0 1 0 0]
 [1 2 1 1]
 [1 1 0 0]
 [2 2 0 1]
 [1 2 0 0]
 [0 2 1 0]
 [0 0 0 1]
 [2 2 1 0]]
0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: Buys, dtype: int32


In [3]:
# applying decision tree classifier
from sklearn.tree import DecisionTreeClassifier as DTC

c = DTC()
c = c.fit(x, y)

#predicting
c.predict([[2, 0, 1, 0],[1,0,0,0]])


#output
# array([0, 1]) --> 0=No , 1=Yes

array([0, 1])